backend:
  name: github
  repo: Ahmad-001A/work755
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "settings"
    label: "Управление сайтом"
    delete: false
    editor:
      preview: false
    files:
      - name: "config"
        label: "Расписание и Стили"
        file: "data/config.json"
        fields:
          - { label: "Главный цвет дизайна (HEX)", name: "accent_color", widget: "string", default: "#6366f1" }
          - { label: "Цвет фона панели (HEX)", name: "glass_bg", widget: "string", default: "#111827" }
          - { label: "Понедельник (через запятую)", name: "mon", widget: "string", default: "ФИЗИКА ОБЩАЯ, ИСТОРИЯ, ХИМИЯ, АЛГЕБРА, ГОСС-ЯЗ" }
          - { label: "Вторник (через запятую)", name: "tue", widget: "string", default: "БИОЛОГИЯ, АНГЛ-ЯЗ, ГЕОМЕТРИЯ, АЛГЕБРА, ФИЗРА" }
          - { label: "Среда (через запятую)", name: "wed", widget: "string", default: "ГЕОМЕТРИЯ, ФИЗИКА ОБЩАЯ, АНГЛ-ЯЗ, РУСС-ЯЗ" }
          - { label: "Четверг (через запятую)", name: "thu", widget: "string", default: "ИСТОРИЯ, КЛ-ЧАС, РУСС-ЯЗ, ГОСС-ПРАВО" }
          - { label: "Пятница (через запятую)", name: "fri", widget: "string", default: "ИКТ, БИОЛОГИЯ, РУСС-ЯЗ, ФИЗРА" }
          - { label: "Суббота (через запятую)", name: "sat", widget: "string", default: "ХИМИЯ, ЧЕРЧЕНИЕ, ГОСС-ЯЗ" }
